In [7]:
import pandas as pd
import numpy as np
from pandas import DataFrame, Series
import numpy.random as random

In [8]:
import kagglehub
from kagglehub import KaggleDatasetAdapter

In [10]:
file_path = "Forest_Area.csv"
# Load the latest version
data = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "kanchana1990/global-forest-insights-1990-2020-fao",
  file_path,
  # Provide any additional arguments like 
  # sql_query or pandas_kwargs. See the 
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

C:\Users\nate8\AppData\Local\Temp\ipykernel_96180\1546295545.py:3: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  data = kagglehub.load_dataset(

In [11]:
print("First 5 records:", data.head())

First 5 records:    CountryID Country and Area  Forest Area, 1990  Forest Area, 2000  \
0        NaN            WORLD         4236433.42         4158049.52
1        4.0      Afghanistan            1208.44            1208.44
2        8.0          Albania             788.80             769.30
3       12.0          Algeria            1667.00            1579.00
4       16.0   American Samoa              18.07              17.73

   Forest Area, 2010 Forest Area, 2015  Forest Area, 2020  \
0         4106316.94                          4058930.81
1            1208.44           1208.44            1208.44
2             782.07            789.19             788.90
3            1918.00              1956            1949.00
4              17.43             17.28              17.13

   Total Land Area, 2020  \
0             13003000.0
1                65286.0
2                 2740.0
3               238174.0
4                   20.0

   Forest Area as a Proportion of Total Land Area, 2020  \
0                                              31.13
1                                               1.85
2                                              28.79
3                                               0.82
4                                              85.65

  Deforestation, 2015-2020 Total Forest Area Affected by Fire, 2015
0                    10200                                    98040
1                      ...                                      ...
2                      ...                                      ...
3                      5.4                                      ...
4                      ...                                        0

In [12]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 239 entries, 0 to 238
Data columns (total 11 columns):
 #   Column                                                Non-Null Count  Dtype
---  ------                                                --------------  -----
 0   CountryID                                             236 non-null    float64
 1   Country and Area                                      237 non-null    str
 2   Forest Area, 1990                                     237 non-null    float64
 3   Forest Area, 2000                                     237 non-null    float64
 4   Forest Area, 2010                                     237 non-null    float64
 5   Forest Area, 2015                                     237 non-null    str
 6   Forest Area, 2020                                     237 non-null    float64
 7   Total Land Area, 2020                                 237 non-null    float64
 8   Forest Area as a Proportion of Total Land Area, 2020  237 non-null    float64
 9   Deforestation, 2015-2020                              237 non-null    str
 10  Total Forest Area Affected by Fire, 2015              237 non-null    str
dtypes: float64(7), str(4)
memory usage: 20.7 KB

In [13]:
data.describe()

,CountryID,"Forest Area, 1990","Forest Area, 2000","Forest Area, 2010","Forest Area, 2020","Total Land Area, 2020","Forest Area as a Proportion of Total Land Area, 2020"
count,236.000000,2.370000e+02,2.370000e+02,2.370000e+02,2.370000e+02,2.370000e+02,237.000000
mean,444.563559,3.575049e+04,3.508903e+04,3.465246e+04,3.425258e+04,1.098799e+05,31.574135
std,253.068287,2.836953e+05,2.784833e+05,2.750633e+05,2.720227e+05,8.577117e+05,24.709003
min,4.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000
25%,229.750000,3.361000e+01,3.370000e+01,3.452000e+01,3.370000e+01,2.430000e+02,10.450000
50%,452.000000,1.188000e+03,1.233000e+03,1.234720e+03,1.237830e+03,7.434000e+03,30.270000
75%,660.500000,8.769170e+03,8.369250e+03,8.468160e+03,8.068160e+03,4.073100e+04,49.780000
max,894.000000,4.236433e+06,4.158050e+06,4.106317e+06,4.058931e+06,1.300300e+07,97.410000

In [15]:
data.head().T

,0,1,2,3,4
CountryID,NaN,4.0,8.0,12.0,16.0
Country and Area,WORLD,Afghanistan,Albania,Algeria,American Samoa
"Forest Area, 1990",4236433.42,1208.44,788.8,1667.0,18.07
"Forest Area, 2000",4158049.52,1208.44,769.3,1579.0,17.73
"Forest Area, 2010",4106316.94,1208.44,782.07,1918.0,17.43
"Forest Area, 2015",,1208.44,789.19,1956,17.28
"Forest Area, 2020",4058930.81,1208.44,788.9,1949.0,17.13
"Total Land Area, 2020",13003000.0,65286.0,2740.0,238174.0,20.0
"Forest Area as a Proportion of Total Land Area, 2020",31.13,1.85,28.79,0.82,85.65
"Deforestation, 2015-2020",10200,...,...,5.4,...
"Total Forest Area Affected by Fire, 2015",98040,...,...,...,0

In [16]:
data['Total Land Area, 2020']

0      13003000.0
1         65286.0
2          2740.0
3        238174.0
4            20.0
          ...
234       52797.0
235       74339.0
236       38685.0
237           NaN
238           NaN
Name: Total Land Area, 2020, Length: 239, dtype: float64

In [20]:
data[['Total Land Area, 2020', 'Forest Area, 2020']]

     Total Land Area, 2020  Forest Area, 2020
0               13003000.0         4058930.81
1                  65286.0            1208.44
2                   2740.0             788.90
3                 238174.0            1949.00
4                     20.0              17.13
..                     ...                ...
234                52797.0             549.00
235                74339.0           44814.03
236                38685.0           17444.58
237                    NaN                NaN
238                    NaN                NaN

[239 rows x 2 columns]

In [21]:
data[0:3]

,CountryID,Country and Area,"Forest Area, 1990","Forest Area, 2000","Forest Area, 2010","Forest Area, 2015","Forest Area, 2020","Total Land Area, 2020","Forest Area as a Proportion of Total Land Area, 2020","Deforestation, 2015-2020","Total Forest Area Affected by Fire, 2015"
0,NaN,WORLD,4236433.42,4158049.52,4106316.94,,4058930.81,13003000.0,31.13,10200,98040
1,4.0,Afghanistan,1208.44,1208.44,1208.44,1208.44,1208.44,65286.0,1.85,...,...
2,8.0,Albania,788.80,769.30,782.07,789.19,788.90,2740.0,28.79,...,...

In [23]:
data.loc[4]

CountryID                                                         16.0
Country and Area                                        American Samoa
Forest Area, 1990                                                18.07
Forest Area, 2000                                                17.73
Forest Area, 2010                                                17.43
Forest Area, 2015                                                17.28
Forest Area, 2020                                                17.13
Total Land Area, 2020                                             20.0
Forest Area as a Proportion of Total Land Area, 2020             85.65
Deforestation, 2015-2020                                           ...
Total Forest Area Affected by Fire, 2015                             0
Name: 4, dtype: object

In [24]:
data.loc[3:8]

,CountryID,Country and Area,"Forest Area, 1990","Forest Area, 2000","Forest Area, 2010","Forest Area, 2015","Forest Area, 2020","Total Land Area, 2020","Forest Area as a Proportion of Total Land Area, 2020","Deforestation, 2015-2020","Total Forest Area Affected by Fire, 2015"
3,12.0,Algeria,1667.00,1579.00,1918.00,1956,1949.00,238174.0,0.82,5.4,...
4,16.0,American Samoa,18.07,17.73,17.43,17.28,17.13,20.0,85.65,...,0
5,20.0,Andorra,16.00,16.00,16.00,16,16.00,47.0,34.04,...,...
6,24.0,Angola,79262.78,77708.61,72158.00,69382.69,66607.38,124670.0,53.43,...,...
7,660.0,Anguilla,5.50,5.50,5.50,5.5,5.50,9.0,61.11,...,...
8,28.0,Antigua and Barbuda,10.11,9.45,8.78,8.45,8.12,44.0,18.45,...,...

In [25]:
data.loc[:, 'Country and Area']

0               WORLD
1         Afghanistan
2             Albania
3             Algeria
4      American Samoa
            ...
234             Yemen
235            Zambia
236          Zimbabwe
237               NaN
238               NaN
Name: Country and Area, Length: 239, dtype: str

In [28]:
data.loc[:, ['Country and Area', 'Forest Area, 2020']]

    Country and Area  Forest Area, 2020
0              WORLD         4058930.81
1        Afghanistan            1208.44
2            Albania             788.90
3            Algeria            1949.00
4     American Samoa              17.13
..               ...                ...
234            Yemen             549.00
235           Zambia           44814.03
236         Zimbabwe           17444.58
237              NaN                NaN
238              NaN                NaN

[239 rows x 2 columns]

In [29]:
data.iloc[0:4, [0, 2]]

   CountryID  Forest Area, 1990
0        NaN         4236433.42
1        4.0            1208.44
2        8.0             788.80
3       12.0            1667.00

In [46]:
data.at[1, 'Forest Area, 2020']

np.float64(1208.44)

In [50]:
print(data['Forest Area, 2020'] >= 1000.0)

0       True
1       True
2      False
3       True
4      False
       ...
234    False
235     True
236     True
237    False
238    False
Name: Forest Area, 2020, Length: 239, dtype: bool

In [51]:
data[(data['Country and Area']== 'Ethiopia') | (data['Country and Area']== 'Brazil' )]

,CountryID,Country and Area,"Forest Area, 1990","Forest Area, 2000","Forest Area, 2010","Forest Area, 2015","Forest Area, 2020","Total Land Area, 2020","Forest Area as a Proportion of Total Land Area, 2020","Deforestation, 2015-2020","Total Forest Area Affected by Fire, 2015"
29,76.0,Brazil,588898.0,551088.6,511580.7,503884.8,496619.6,835814.00,59.42,1695.7,32998.07
68,231.0,Ethiopia,19258.5,18528.5,17798.5,17433.5,17068.5,111971.55,15.24,92,...

In [52]:
data.isnull().sum()

CountryID                                               3
Country and Area                                        2
Forest Area, 1990                                       2
Forest Area, 2000                                       2
Forest Area, 2010                                       2
Forest Area, 2015                                       2
Forest Area, 2020                                       2
Total Land Area, 2020                                   2
Forest Area as a Proportion of Total Land Area, 2020    2
Deforestation, 2015-2020                                2
Total Forest Area Affected by Fire, 2015                2
dtype: int64

In [53]:
data.sort_values(by='Forest Area, 2020', ascending=False).head()

,CountryID,Country and Area,"Forest Area, 1990","Forest Area, 2000","Forest Area, 2010","Forest Area, 2015","Forest Area, 2020","Total Land Area, 2020","Forest Area as a Proportion of Total Land Area, 2020","Deforestation, 2015-2020","Total Forest Area Affected by Fire, 2015"
0,NaN,WORLD,4236433.42,4158049.52,4106316.94,,4058930.81,13003000.0,31.13,10200,98040
174,643.0,Russian Federation,808949.90,809268.50,815135.60,814930.46,815311.60,1637687.0,49.78,0,2748.9
29,76.0,Brazil,588898.00,551088.60,511580.70,503884.8,496619.60,835814.0,59.42,1695.7,32998.07
38,124.0,Canada,348272.93,347801.97,347322.21,347115.71,346928.10,909351.0,38.15,37.52,3861.65
225,840.0,United States of America,302450.00,303536.00,308720.00,310095,309795.00,914742.0,33.87,...,4097.65